# Generated by Django 5.0.1 on 2024-02-01 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
